import { useState, useCallback } from "react";

interface UseGeminiImagePromptState {
  loading: boolean;
  error: string | null;
  prompt: string | null;
}

interface GeminiImagePromptOptions {
  currentImageBase64?: string;
  userLevel?: number;
  userName?: string;
  onError?: (error: Error) => void;
}

/**
 * Hook for using Google Gemini to generate creative image prompts
 * for profile picture generation based on the current profile picture and user level
 *
 * @returns Object with loading state, error, prompt, and function to generate prompt
 */
export function useGeminiImagePrompt() {
  const [state, setState] = useState<UseGeminiImagePromptState>({
    loading: false,
    error: null,
    prompt: null,
  });

  const generatePrompt = useCallback(
    async (options: GeminiImagePromptOptions): Promise<string | null> => {
      const {
        currentImageBase64,
        userLevel = 1,
        userName = "User",
        onError,
      } = options;

      setState({ loading: true, error: null, prompt: null });

      try {
        // Get the Gemini API key from environment variables
        const apiKey = process.env.REACT_APP_GEMINI_API_KEY;
        if (!apiKey) {
          throw new Error(
            "Gemini API key not configured. Please set REACT_APP_GEMINI_API_KEY environment variable.",
          );
        }

        // Build the prompt for Gemini
        const systemPrompt = `You are a creative AI assistant that generates detailed image generation prompts.
Your task is to create a visually descriptive prompt that will be used to generate a profile picture.
The prompt should be creative, inspiring, and reflect an achievement/level-up moment.
Keep the prompt concise but vivid - around 50-150 words.
Focus on visual qualities, art style, mood, and any relevant themes.`;

        let userPrompt = `Generate a creative image prompt for a profile picture for a user named "${userName}" who just reached level ${userLevel}. `;

        if (currentImageBase64) {
          userPrompt += `They currently have a profile picture (provided as base64). `;
          userPrompt += `Create an evolved/upgraded version of their current style to reflect their level-up achievement. `;
          userPrompt += `The new image should maintain some essence of the original while showing growth and progression.`;
        } else {
          userPrompt += `Create a completely new and unique profile picture that represents achievement, growth, and level ${userLevel}. `;
          userPrompt += `Make it inspiring and celebratory.`;
        }

        // Prepare the request to Gemini API
        const requestBody: any = {
          contents: [
            {
              role: "user",
              parts: [
                {
                  text: userPrompt,
                },
              ],
            },
          ],
          systemInstruction: {
            parts: [
              {
                text: systemPrompt,
              },
            ],
          },
          generationConfig: {
            temperature: 0.7,
            topP: 0.8,
            maxOutputTokens: 256,
          },
        };

        // If we have an image, add it to the request
        if (currentImageBase64) {
          // Extract the base64 data (remove data:image/...;base64, prefix if present)
          const base64Data = currentImageBase64.includes(",")
            ? currentImageBase64.split(",")[1]
            : currentImageBase64;

          requestBody.contents[0].parts.push({
            inlineData: {
              mimeType: "image/jpeg",
              data: base64Data,
            },
          });
        }

        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`,
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify(requestBody),
          },
        );

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(
            `Gemini API error: ${
              errorData.error?.message || response.statusText
            }`,
          );
        }

        const data = await response.json();

        // Extract the generated text from Gemini's response
        const generatedPrompt =
          data?.candidates?.[0]?.content?.parts?.[0]?.text || "";

        if (!generatedPrompt) {
          throw new Error("No prompt generated by Gemini");
        }

        setState({
          loading: false,
          error: null,
          prompt: generatedPrompt,
        });

        return generatedPrompt;
      } catch (error) {
        const err = error instanceof Error ? error : new Error(String(error));
        setState({
          loading: false,
          error: err.message,
          prompt: null,
        });

        if (onError) {
          onError(err);
        }

        return null;
      }
    },
    [],
  );

  const resetState = useCallback(() => {
    setState({
      loading: false,
      error: null,
      prompt: null,
    });
  }, []);

  return {
    ...state,
    generatePrompt,
    resetState,
  };
}
